<a href="https://colab.research.google.com/github/DEEPESH98/Basic-Python-Programs/blob/master/numpy_file4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
print("ujjwal")

ujjwal


In [0]:
import numpy

In [0]:
import numpy as np

In [0]:
a=np.array([2,7,1,99,4])

In [0]:
type(a)

numpy.ndarray

In [0]:
b=np.array([12,17,11,199,14])

In [0]:
a

array([ 2,  7,  1, 99,  4])

In [0]:
b

array([ 12,  17,  11, 199,  14])

In [0]:
a[0]

2

In [0]:
b[0]

12

In [0]:
a+b

array([ 14,  24,  12, 298,  18])

In [0]:
a*2

array([  4,  14,   2, 198,   8])

In [0]:
a**2

array([   4,   49,    1, 9801,   16])

In [0]:
c=a+b

In [0]:
print(c)

[ 14  24  12 298  18]


In [0]:
m=a*b

In [0]:
print(m)

[   24   119    11 19701    56]


In [0]:
a5=a+5

In [0]:
print(a5)

[  7  12   6 104   9]


In [0]:
#two demission

In [0]:
import numpy as np

In [0]:
x=np.array([[2,5,8],[3,6,1]])

In [0]:
#this is 2*3 matrix

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:

x[0]

array([2, 5, 8])

In [0]:
x[0][0]

2

In [0]:
# zero row ka zero coloum

In [0]:
x[1]

array([3, 6, 1])

In [0]:
x+7

array([[ 9, 12, 15],
       [10, 13,  8]])

In [0]:
# first row +7

In [0]:
x*2

array([[ 4, 10, 16],
       [ 6, 12,  2]])

In [0]:
x**2

array([[ 4, 25, 64],
       [ 9, 36,  1]])

In [0]:
#new 2d array

In [0]:
z=np.array([[2,7],[3,8],[4,9],[9,4]])

In [0]:
z

array([[2, 7],
       [3, 8],
       [4, 9],
       [9, 4]])

In [0]:
x.shape

(2, 3)

In [0]:
z.shape

(4, 2)

In [0]:
x

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
z[0:2] #for range 0 sy 2

array([[2, 7],
       [3, 8]])

In [0]:
z[0:] #for all rows

array([[2, 7],
       [3, 8],
       [4, 9],
       [9, 4]])

In [0]:
z[0:,0] #sirf coloum 0 print k liyy comma

array([2, 3, 4, 9])

In [0]:
z[0:2,0] #2row mey 2 coloumn tk 

array([2, 3])

In [0]:
x[0:,1]

array([5, 6])

In [0]:
x[0:,0:2]  #2 row and 2 coloum

array([[2, 5],
       [3, 6]])

In [0]:
x[0:,[0,2]] # for first and last coloumn

array([[2, 8],
       [3, 1]])

In [0]:
z[[0,2]]# z ki row 1 and row 3

array([[2, 7],
       [4, 9]])

In [0]:
z

array([[2, 7],
       [3, 8],
       [4, 9],
       [9, 4]])

In [0]:



z[[0,3],1]# z column ka 1 and last row value

array([7, 4])

In [0]:
# for change demission 2*3 to 3*2 use x.reshape(3,2)

In [0]:
x.reshape(3,2)

array([[2, 5],
       [8, 3],
       [6, 1]])

In [0]:
x.reshape(2,3)

array([[2, 5, 8],
       [3, 6, 1]])

In [0]:
# task:-- 1. user sy row and coloumn k input and kitny combination bn sakty hai in k unko 2 d mey print kraana hai 

# 2. generate 3*2 and 2*5 2d array with random element and save this data into 2 seprate file
# 3. 

In [0]:
np.zeros((3,6))  # 3*6 matrix for 0 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.ones((5,2))  # 5row and 2 col. for 1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
np.full((4,5),9)  #4*5 ki matrix 9 k  liyy

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [0]:
for i in dir(np):
  if 'zer' in i:
    print(i)

count_nonzero
flatnonzero
nonzero
trim_zeros
zeros
zeros_like


In [0]:
[i for i in dir(np) if 'zer' in i ]

['count_nonzero',
 'flatnonzero',
 'nonzero',
 'trim_zeros',
 'zeros',
 'zeros_like']

In [0]:
#  data processing and visulization in next line popular lib.:----- mpld3,mataploitlib,seaboxn,gnuplot,dash

In [0]:
#problem 1 parctice in next line---------->>>>>>>>>>>>>






#__________________________________------------------------------------>>>>>>>>>>>>>>>>>>>>>>>>>>

In [0]:
import numpy as np

In [0]:
import random

In [0]:
np.random.random((3,6))

array([[0.46799182, 0.60698515, 0.69349722, 0.67715155, 0.46420043,
        0.76499023],
       [0.85360108, 0.72106928, 0.28105106, 0.35495973, 0.59521123,
        0.27325987],
       [0.41148162, 0.57654939, 0.68815301, 0.93170454, 0.03695198,
        0.97880385]])

In [0]:
x=int(input())

4


In [0]:
x=np.random.random((3,6))

In [0]:
x

array([[0.63605854, 0.97501089, 0.86543764, 0.75966237, 0.57458478,
        0.62964534],
       [0.63247172, 0.39137598, 0.45710083, 0.83482653, 0.27540589,
        0.99832002],
       [0.73385586, 0.74342385, 0.58225918, 0.73902867, 0.33042485,
        0.20891293]])

In [0]:
x=int(input())

3


In [0]:
y=int(input())

6


In [0]:
m=np.random.random((x,y))

In [0]:
m

array([[0.4353528 , 0.81886162, 0.04476522, 0.74097879, 0.26467632,
        0.78007116],
       [0.58812347, 0.55237764, 0.29487785, 0.97955369, 0.80942951,
        0.3302932 ],
       [0.55163365, 0.97429348, 0.87519838, 0.66468294, 0.90979755,
        0.98648854]])

In [0]:
x=input()

4,3,2,4,2,4,2


In [0]:
y=input()

3,4,5,6,2,2,21,5,6,8,10


In [0]:
m=np.array((x,y))

In [0]:
m

array(['4,3,2,4,2,4,2', '3,4,5,6,2,2,21,5,6,8,10'], dtype='<U23')

In [0]:
y=np.input((x,y))

AttributeError: ignored

In [0]:
y=np.input((3,6))

AttributeError: ignored

In [0]:
x=input()
y=input()
m=(x,y)
m=np.random.random((3,6))

2,2,22,2,2,2,
3,3,3,3,3,3,3


In [0]:
m=np.array((x,y))

In [0]:
m

array(['2,2,22,2,2,2,', '3,3,3,3,3,3,3'], dtype='<U13')

In [0]:
m=((x,y))

In [0]:
m=np.random.random((3,6))

In [0]:
m

array([[0.98999917, 0.03430442, 0.08224836, 0.38102708, 0.1597583 ,
        0.3479872 ],
       [0.35109087, 0.19749429, 0.58340915, 0.05753239, 0.56946683,
        0.35352499],
       [0.17881831, 0.10872546, 0.19000512, 0.76037271, 0.66057577,
        0.00510928]])

In [0]:
x=input()

3


In [0]:
y=input()

4


In [0]:
import numpy as np

p=np.random.random((x,y))

TypeError: ignored

In [0]:
import numpy as np 

In [0]:
x=int(input())

4


In [0]:
y=int(input())

4


In [0]:
p=np.random.random((x,y))

In [0]:
p

array([[0.75062382, 0.30428814, 0.3174274 , 0.63967719],
       [0.33468189, 0.68333226, 0.88500196, 0.17878562],
       [0.11703095, 0.16081318, 0.27180442, 0.97249745],
       [0.97311055, 0.42763197, 0.76506302, 0.45887797]])